"""Added Image for each Post

Revision ID: 654a6b1e7124
Revises: 2a96c686beb5
Create Date: 2026-06-28 15:56:09.895188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '654a6b1e7124'
down_revision: Union[str, Sequence[str], None] = '2a96c686beb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('image_file', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'image_file')
    # ### end Alembic commands ###
